name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v2

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2

      - name: Install & setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm install
      - name: Run prettier --check
        run: npm run prettier-check
